In [1]:
import pandas as pd

In [9]:
df = pd.read_excel(
    r"D:\data-science-journey\Data_Science\Data\Pandas_Student_Analytics_Dataset.xlsx",
    engine="openpyxl"
)

In [12]:
df.head(10)
df.tail(10)

,StudentID,EnrollmentNo,StudentName,Gender,Age,City,CollegeName,Department,Semester,AdmissionDate,...,Grade,Status,FeesTotal,FeesPaid,FeesDue,Scholarship,PlacementStatus,InternshipPerformance,ProjectScore,Backlogs
1190,STU1191,GTU26001191,Yash Trivedi,Male,22,Bhavnagar,Government Engineering College,Electrical,8,2025-07-30,...,C,Pass,40000,26790,13210,OBC,Higher Studies,Average,74,1
1191,STU1192,GTU26001192,Aryan Trivedi,Male,18,Surat,Government Engineering College,Information Technology,8,2026-01-23,...,A,Pass,45000,24872,20128,SC/ST,Higher Studies,Excellent,52,2
1192,STU1193,GTU26001193,Krishna Solanki,Male,20,Mehsana,Alpha College,Computer,8,2026-03-17,...,A,Pass,25000,23462,1538,SC/ST,Seeking Job,Good,84,2
1193,STU1194,GTU26001194,Ananya Shah,Female,24,Rajkot,Alpha College,Electronics,5,2026-02-12,...,A,Pass,40000,36521,3479,EWS,Placed,Good,86,0
1194,STU1195,GTU26001195,Dhruv Desai,Male,19,Rajkot,LDRP Institute,Civil,6,2026-04-13,...,A,Pass,30000,22960,7040,SC/ST,Placed,Good,87,2
1195,STU1196,GTU26001196,Rahul Joshi,Male,23,Rajkot,Alpha College,Computer,7,2025-11-25,...,B,Pass,25000,13627,11373,OBC,Seeking Job,Average,82,1
1196,STU1197,GTU26001197,Vivaan Panchal,Male,22,Bhavnagar,LJ University,Computer,6,2025-12-18,...,A+,Pass,25000,23975,1025,OBC,Placed,Very Good,86,1
1197,STU1198,GTU26001198,Rahul Trivedi,Male,18,Gandhinagar,LDRP Institute,Civil,8,2026-03-27,...,B,Pass,45000,30283,14717,EWS,Seeking Job,Very Good,56,1
1198,STU1199,GTU26001199,Aryan Desai,Male,22,Himatnagar,Government Engineering College,Electronics,8,2025-11-02,...,B,Pass,45000,41487,3513,SC/ST,Higher Studies,Good,95,2
1199,STU1200,GTU26001200,Yash Panchal,Male,21,Rajkot,LDRP Institute,Computer,7,2026-01-07,...,B,Pass,40000,30278,9722,OBC,Higher Studies,Good,80,2

In [16]:
df.shape

(1200, 26)

In [22]:
df.columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 26 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   StudentID              1200 non-null   object
 1   EnrollmentNo           1200 non-null   object
 2   StudentName            1200 non-null   object
 3   Gender                 1200 non-null   object
 4   Age                    1200 non-null   int64
 5   City                   1200 non-null   object
 6   CollegeName            1200 non-null   object
 7   Department             1200 non-null   object
 8   Semester               1200 non-null   int64
 9   AdmissionDate          1200 non-null   object
 10  AttendancePct          1200 non-null   int64
 11  InternalMarks          1200 non-null   int64
 12  PracticalMarks         1200 non-null   int64
 13  FinalExamMarks         1200 non-null   int64
 14  TotalMarks             1200 non-null   int64
 15  Percentage             1200 non-null   int64
 16  Grade                  1200 non-null   object
 17  Status                 1200 non-null   object
 18  FeesTotal              1200 non-null   int64
 19  FeesPaid               1200 non-null   int64
 20  FeesDue                1200 non-null   int64
 21  Scholarship            974 non-null    object
 22  PlacementStatus        1200 non-null   object
 23  InternshipPerformance  1200 non-null   object
 24  ProjectScore           1200 non-null   int64
 25  Backlogs               1200 non-null   int64
dtypes: int64(13), object(13)
memory usage: 243.9+ KB

# Module 2

In [24]:
df.memory_usage(deep=True)
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 26 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   StudentID              1200 non-null   object
 1   EnrollmentNo           1200 non-null   object
 2   StudentName            1200 non-null   object
 3   Gender                 1200 non-null   object
 4   Age                    1200 non-null   int64
 5   City                   1200 non-null   object
 6   CollegeName            1200 non-null   object
 7   Department             1200 non-null   object
 8   Semester               1200 non-null   int64
 9   AdmissionDate          1200 non-null   object
 10  AttendancePct          1200 non-null   int64
 11  InternalMarks          1200 non-null   int64
 12  PracticalMarks         1200 non-null   int64
 13  FinalExamMarks         1200 non-null   int64
 14  TotalMarks             1200 non-null   int64
 15  Percentage             1200 non-null   int64
 16  Grade                  1200 non-null   object
 17  Status                 1200 non-null   object
 18  FeesTotal              1200 non-null   int64
 19  FeesPaid               1200 non-null   int64
 20  FeesDue                1200 non-null   int64
 21  Scholarship            974 non-null    object
 22  PlacementStatus        1200 non-null   object
 23  InternshipPerformance  1200 non-null   object
 24  ProjectScore           1200 non-null   int64
 25  Backlogs               1200 non-null   int64
dtypes: int64(13), object(13)
memory usage: 1.1 MB

In [28]:
# df.select_dtypes(include=['number']).columns.to_list()
df.select_dtypes(include=['object','category']).columns.to_list()

['StudentID',
 'EnrollmentNo',
 'StudentName',
 'Gender',
 'City',
 'CollegeName',
 'Department',
 'AdmissionDate',
 'Grade',
 'Status',
 'Scholarship',
 'PlacementStatus',
 'InternshipPerformance']

In [29]:
df['City'].unique()

array(['Ahmedabad', 'Mehsana', 'Himatnagar', 'Rajkot', 'Gandhinagar',
       'Bhavnagar', 'Vadodara', 'Surat', 'Patan', 'Junagadh'],
      dtype=object)

# Module 3

In [31]:
df.isnull().sum()

StudentID                  0
EnrollmentNo               0
StudentName                0
Gender                     0
Age                        0
City                       0
CollegeName                0
Department                 0
Semester                   0
AdmissionDate              0
AttendancePct              0
InternalMarks              0
PracticalMarks             0
FinalExamMarks             0
TotalMarks                 0
Percentage                 0
Grade                      0
Status                     0
FeesTotal                  0
FeesPaid                   0
FeesDue                    0
Scholarship              226
PlacementStatus            0
InternshipPerformance      0
ProjectScore               0
Backlogs                   0
dtype: int64

In [35]:
df.drop_duplicates()

,StudentID,EnrollmentNo,StudentName,Gender,Age,City,CollegeName,Department,Semester,AdmissionDate,...,Grade,Status,FeesTotal,FeesPaid,FeesDue,Scholarship,PlacementStatus,InternshipPerformance,ProjectScore,Backlogs
0,STU0001,GTU26000001,Vivaan Desai,Male,24,Ahmedabad,Marwadi University,Electrical,7,2025-11-22,...,A,Pass,35000,17529,17471,Merit,Placed,Good,85,2
1,STU0002,GTU26000002,Ananya Mehta,Female,18,Ahmedabad,Ganpat University,Electronics,8,2025-07-23,...,C,Pass,45000,30373,14627,NaN,Seeking Job,Very Good,58,0
2,STU0003,GTU26000003,Sneha Panchal,Female,20,Mehsana,Alpha College,Information Technology,7,2025-06-07,...,A+,Pass,25000,22595,2405,EWS,Higher Studies,Average,83,3
3,STU0004,GTU26000004,Neha Solanki,Female,21,Himatnagar,Silver Oak University,Mechanical,7,2026-03-11,...,A+,Pass,30000,14706,15294,NaN,Seeking Job,Average,74,2
4,STU0005,GTU26000005,Aarav Joshi,Male,20,Rajkot,Marwadi University,Electrical,5,2026-04-24,...,A,Pass,25000,24682,318,OBC,Seeking Job,Very Good,84,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,STU1196,GTU26001196,Rahul Joshi,Male,23,Rajkot,Alpha College,Computer,7,2025-11-25,...,B,Pass,25000,13627,11373,OBC,Seeking Job,Average,82,1
1196,STU1197,GTU26001197,Vivaan Panchal,Male,22,Bhavnagar,LJ University,Computer,6,2025-12-18,...,A+,Pass,25000,23975,1025,OBC,Placed,Very Good,86,1
1197,STU1198,GTU26001198,Rahul Trivedi,Male,18,Gandhinagar,LDRP Institute,Civil,8,2026-03-27,...,B,Pass,45000,30283,14717,EWS,Seeking Job,Very Good,56,1
1198,STU1199,GTU26001199,Aryan Desai,Male,22,Himatnagar,Government Engineering College,Electronics,8,2025-11-02,...,B,Pass,45000,41487,3513,SC/ST,Higher Studies,Good,95,2
1199,STU1200,GTU26001200,Yash Panchal,Male,21,Rajkot,LDRP Institute,Computer,7,2026-01-07,...,B,Pass,40000,30278,9722,OBC,Higher Studies,Good,80,2

In [44]:
df['AttendancePct'].isnull().sum()
df['Scholarship'].fillna("None")

0       Merit
1        None
2         EWS
3        None
4         OBC
        ...
1195      OBC
1196      OBC
1197      EWS
1198    SC/ST
1199      OBC
Name: Scholarship, Length: 1200, dtype: object

In [50]:
df['AdmissionDate']  = pd.to_datetime(df['AdmissionDate'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 26 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   StudentID              1200 non-null   object
 1   EnrollmentNo           1200 non-null   object
 2   StudentName            1200 non-null   object
 3   Gender                 1200 non-null   object
 4   Age                    1200 non-null   int64
 5   City                   1200 non-null   object
 6   CollegeName            1200 non-null   object
 7   Department             1200 non-null   object
 8   Semester               1200 non-null   int64
 9   AdmissionDate          1200 non-null   datetime64[ns]
 10  AttendancePct          1200 non-null   int64
 11  InternalMarks          1200 non-null   int64
 12  PracticalMarks         1200 non-null   int64
 13  FinalExamMarks         1200 non-null   int64
 14  TotalMarks             1200 non-null   int64
 15  Percentage             1200 non-null   int64
 16  Grade                  1200 non-null   object
 17  Status                 1200 non-null   object
 18  FeesTotal              1200 non-null   int64
 19  FeesPaid               1200 non-null   int64
 20  FeesDue                1200 non-null   int64
 21  Scholarship            974 non-null    object
 22  PlacementStatus        1200 non-null   object
 23  InternshipPerformance  1200 non-null   object
 24  ProjectScore           1200 non-null   int64
 25  Backlogs               1200 non-null   int64
dtypes: datetime64[ns](1), int64(13), object(12)
memory usage: 243.9+ KB

In [ ]:
df.rename(columns={"AttendancePct": "Attendance"}, inplace=True)

,StudentID,EnrollmentNo,StudentName,Gender,Age,City,CollegeName,Department,Semester,AdmissionDate,...,Grade,Status,FeesTotal,FeesPaid,FeesDue,Scholarship,PlacementStatus,InternshipPerformance,ProjectScore,Backlogs
0,STU0001,GTU26000001,Vivaan Desai,Male,24,Ahmedabad,Marwadi University,Electrical,7,2025-11-22,...,A,Pass,35000,17529,17471,Merit,Placed,Good,85,2
1,STU0002,GTU26000002,Ananya Mehta,Female,18,Ahmedabad,Ganpat University,Electronics,8,2025-07-23,...,C,Pass,45000,30373,14627,NaN,Seeking Job,Very Good,58,0
2,STU0003,GTU26000003,Sneha Panchal,Female,20,Mehsana,Alpha College,Information Technology,7,2025-06-07,...,A+,Pass,25000,22595,2405,EWS,Higher Studies,Average,83,3
3,STU0004,GTU26000004,Neha Solanki,Female,21,Himatnagar,Silver Oak University,Mechanical,7,2026-03-11,...,A+,Pass,30000,14706,15294,NaN,Seeking Job,Average,74,2
4,STU0005,GTU26000005,Aarav Joshi,Male,20,Rajkot,Marwadi University,Electrical,5,2026-04-24,...,A,Pass,25000,24682,318,OBC,Seeking Job,Very Good,84,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,STU1196,GTU26001196,Rahul Joshi,Male,23,Rajkot,Alpha College,Computer,7,2025-11-25,...,B,Pass,25000,13627,11373,OBC,Seeking Job,Average,82,1
1196,STU1197,GTU26001197,Vivaan Panchal,Male,22,Bhavnagar,LJ University,Computer,6,2025-12-18,...,A+,Pass,25000,23975,1025,OBC,Placed,Very Good,86,1
1197,STU1198,GTU26001198,Rahul Trivedi,Male,18,Gandhinagar,LDRP Institute,Civil,8,2026-03-27,...,B,Pass,45000,30283,14717,EWS,Seeking Job,Very Good,56,1
1198,STU1199,GTU26001199,Aryan Desai,Male,22,Himatnagar,Government Engineering College,Electronics,8,2025-11-02,...,B,Pass,45000,41487,3513,SC/ST,Higher Studies,Good,95,2
1199,STU1200,GTU26001200,Yash Panchal,Male,21,Rajkot,LDRP Institute,Computer,7,2026-01-07,...,B,Pass,40000,30278,9722,OBC,Higher Studies,Good,80,2