In [1]:
import pandas as pd 
import numpy as np

In [65]:
df = pd.read_csv(r"D:\data-science-journey\Data_Science\Data\Flight_Booking_Advanced_Dirty_Dataset_5500_Records.csv")

In [66]:
# Count total bookings.
df.shape[0]

5500

In [67]:
df['Name_Length'] = df['FlightName'].apply(len)

In [68]:
df['Gender'].dropna()
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [69]:
df['Gender'] = df['Gender'].map({
    'Male': 'M',
    'Female': 'F'
})
df['Gender']

0       M
1       F
2       F
3       F
4       F
       ..
5495    F
5496    F
5497    M
5498    F
5499    M
Name: Gender, Length: 5500, dtype: object

In [70]:
# merge()

# Used to combine two DataFrames based on a common column.

In [71]:
# pivot_table()

# Used to create a summarized table from a DataFrame.

pd.pivot_table(
    df,
    values='TicketPrice',
    index='SeatClass',
    aggfunc='mean'
)

                  TicketPrice
SeatClass
Business         37425.493682
Economy          37215.581790
First Class      37193.058824
Premium Economy  37975.235388

In [72]:
pd.crosstab(df['Gender'], df['SeatClass'])

SeatClass  Business  Economy  First Class  Premium Economy
Gender
F               618      649          594              667
M               569      647          613              582

In [73]:
# age = pd.to_numeric(df['Age'], errors='coerce')

# df.query("Age > 30")

In [74]:
# loc[]

# Used to select rows and columns using labels/conditions.

df.loc[0]
df.loc[age > 30]

,BookingID,BookingDate,CustomerID,CustomerName,Gender,Age,MobileNo,EmailID,City,Country,...,SeatClass,SeatNumber,PNRNumber,TicketPrice,TaxAmount,TotalAmount,PaymentMode,PaymentStatus,BookingStatus,Name_Length
0,1690,2025-11-25,CUST001690,Bahadurjit Swamy,M,48.0,4630329843.0,rgoda@example.com,Berhampore,UK,...,First Class,40A,PNR7922321,24610,1230.50,25840.50,Net Banking,Pending,Waiting,18
1,2399,2026-05-21,CUST002399,NaN,F,33.0,9420542745.0,om95@example.com,Mysore,Thailand,...,Economy,10F,PNR1694734,71893,3594.65,75487.65,Debit Card,Refunded,Waiting,14
3,2506,2026-05-30,CUST002506,Omya Varkey,F,48.0,3151414768.0,user@,Satara,India,...,First Class,32C,PNR8326876,40021,2001.05,42022.05,Credit Card,Pending,NaN,9
4,1496,2025-06-25,CUST001496,Tanmayi Apte,F,58.0,5194803805.0,NaN,Imphal,UK,...,NaN,37D,PNR9053659,69585,3479.25,73064.25,Credit Card,Refunded,Waiting,8
5,2675,2026-03-06,CUST002675,NaN,F,33.0,6504672104.0,george81@example.org,Siliguri,UK,...,Economy,2F,PNR9647184,48815,2440.75,51255.75,UPI,Paid,Cancelled,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5495,4172,2026-01-05,CUST004172,Gayathri Ram,F,39.0,6442065575.0,abcgmail.com,Shimoga,India,...,Economy,12B,PNR3576254,11601,580.05,12181.05,Net Banking,Refunded,Waiting,7
5496,600,2026-01-13,CUST000600,Veda Reddy,F,63.0,4801278694.0,demo#mail.com,Satna,Singapore,...,Business,49D,PNR3086789,3612,180.60,3792.60,Credit Card,Pending,Confirmed,8
5497,1362,2026-06-01,CUST001362,Max Natt,M,52.0,6262413293.0,ucchalvyas@example.org,Aurangabad,Thailand,...,Economy,33C,PNR1028137,44625,2231.25,46856.25,Debit Card,Paid,Confirmed,12
5498,1548,2025-10-24,CUST001548,Rachana Sabharwal,F,32.0,2155039061.0,dateanamika@example.net,Pimpri-Chinchwad,UAE,...,Business,4F,PNR1758138,55615,2780.75,58395.75,Net Banking,Paid,Cancelled,13
5499,4960,2026-05-11,CUST004960,Waida Yadav,M,68.0,2139323697.0,demo#mail.com,Mysore,UAE,...,Business,20C,PNR8515395,26254,1312.70,27566.70,UPI,Refunded,Waiting,13

In [75]:
# iloc[]

# Used to select rows and columns using integer positions.

df.iloc[0]

BookingID                                                       1690
BookingDate                                               2025-11-25
CustomerID                                                CUST001690
CustomerName                                        Bahadurjit Swamy
Gender                                                             M
Age                                                             48.0
MobileNo                                                4630329843.0
EmailID                                            rgoda@example.com
City                                                      Berhampore
Country                                                           UK
FlightID                                                    FL001690
FlightName                                        Singapore Airlines
FlightNumber                                                  SG2109
SourceCity                                                 Ahmedabad
SourceAirport         Sardar Vallabhbhai Patel International Airport
DestinationCity                                                  NaN
DestinationAirport                                  Heathrow Airport
FlightDate                                                2025-11-29
DepartureTime                                                  14:00
ArrivalTime                                                    19:00
SeatClass                                                First Class
SeatNumber                                                       40A
PNRNumber                                                 PNR7922321
TicketPrice                                                    24610
TaxAmount                                                     1230.5
TotalAmount                                                  25840.5
PaymentMode                                              Net Banking
PaymentStatus                                                Pending
BookingStatus                                                Waiting
Name_Length                                                       18
Name: 0, dtype: object

In [76]:
# reset_index()

# Used to reset the DataFrame index back to 0, 1, 2....

df = df.reset_index()
df

,index,BookingID,BookingDate,CustomerID,CustomerName,Gender,Age,MobileNo,EmailID,City,...,SeatClass,SeatNumber,PNRNumber,TicketPrice,TaxAmount,TotalAmount,PaymentMode,PaymentStatus,BookingStatus,Name_Length
0,0,1690,2025-11-25,CUST001690,Bahadurjit Swamy,M,48.0,4630329843.0,rgoda@example.com,Berhampore,...,First Class,40A,PNR7922321,24610,1230.50,25840.50,Net Banking,Pending,Waiting,18
1,1,2399,2026-05-21,CUST002399,NaN,F,33.0,9420542745.0,om95@example.com,Mysore,...,Economy,10F,PNR1694734,71893,3594.65,75487.65,Debit Card,Refunded,Waiting,14
2,2,1181,2025-11-04,CUST001181,Diya Goel,F,30.0,3844774388.0,samraindira@example.net,Medininagar,...,Business,49B,PNR1281400,67601,3380.05,70981.05,Debit Card,Pending,Waiting,9
3,3,2506,2026-05-30,CUST002506,Omya Varkey,F,48.0,3151414768.0,user@,Satara,...,First Class,32C,PNR8326876,40021,2001.05,42022.05,Credit Card,Pending,NaN,9
4,4,1496,2025-06-25,CUST001496,Tanmayi Apte,F,58.0,5194803805.0,NaN,Imphal,...,NaN,37D,PNR9053659,69585,3479.25,73064.25,Credit Card,Refunded,Waiting,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5495,5495,4172,2026-01-05,CUST004172,Gayathri Ram,F,39.0,6442065575.0,abcgmail.com,Shimoga,...,Economy,12B,PNR3576254,11601,580.05,12181.05,Net Banking,Refunded,Waiting,7
5496,5496,600,2026-01-13,CUST000600,Veda Reddy,F,63.0,4801278694.0,demo#mail.com,Satna,...,Business,49D,PNR3086789,3612,180.60,3792.60,Credit Card,Pending,Confirmed,8
5497,5497,1362,2026-06-01,CUST001362,Max Natt,M,52.0,6262413293.0,ucchalvyas@example.org,Aurangabad,...,Economy,33C,PNR1028137,44625,2231.25,46856.25,Debit Card,Paid,Confirmed,12
5498,5498,1548,2025-10-24,CUST001548,Rachana Sabharwal,F,32.0,2155039061.0,dateanamika@example.net,Pimpri-Chinchwad,...,Business,4F,PNR1758138,55615,2780.75,58395.75,Net Banking,Paid,Cancelled,13
5499,5499,4960,2026-05-11,CUST004960,Waida Yadav,M,68.0,2139323697.0,demo#mail.com,Mysore,...,Business,20C,PNR8515395,26254,1312.70,27566.70,UPI,Refunded,Waiting,13

In [77]:
# set_index()

# Used to make a column the DataFrame index.
df = df.set_index('CustomerID')
df

,index,BookingID,BookingDate,CustomerName,Gender,Age,MobileNo,EmailID,City,Country,...,SeatClass,SeatNumber,PNRNumber,TicketPrice,TaxAmount,TotalAmount,PaymentMode,PaymentStatus,BookingStatus,Name_Length
CustomerID,,,,,,,,,,,,,,,,,,,,,
CUST001690,0,1690,2025-11-25,Bahadurjit Swamy,M,48.0,4630329843.0,rgoda@example.com,Berhampore,UK,...,First Class,40A,PNR7922321,24610,1230.50,25840.50,Net Banking,Pending,Waiting,18
CUST002399,1,2399,2026-05-21,NaN,F,33.0,9420542745.0,om95@example.com,Mysore,Thailand,...,Economy,10F,PNR1694734,71893,3594.65,75487.65,Debit Card,Refunded,Waiting,14
CUST001181,2,1181,2025-11-04,Diya Goel,F,30.0,3844774388.0,samraindira@example.net,Medininagar,UK,...,Business,49B,PNR1281400,67601,3380.05,70981.05,Debit Card,Pending,Waiting,9
CUST002506,3,2506,2026-05-30,Omya Varkey,F,48.0,3151414768.0,user@,Satara,India,...,First Class,32C,PNR8326876,40021,2001.05,42022.05,Credit Card,Pending,NaN,9
CUST001496,4,1496,2025-06-25,Tanmayi Apte,F,58.0,5194803805.0,NaN,Imphal,UK,...,NaN,37D,PNR9053659,69585,3479.25,73064.25,Credit Card,Refunded,Waiting,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CUST004172,5495,4172,2026-01-05,Gayathri Ram,F,39.0,6442065575.0,abcgmail.com,Shimoga,India,...,Economy,12B,PNR3576254,11601,580.05,12181.05,Net Banking,Refunded,Waiting,7
CUST000600,5496,600,2026-01-13,Veda Reddy,F,63.0,4801278694.0,demo#mail.com,Satna,Singapore,...,Business,49D,PNR3086789,3612,180.60,3792.60,Credit Card,Pending,Confirmed,8
CUST001362,5497,1362,2026-06-01,Max Natt,M,52.0,6262413293.0,ucchalvyas@example.org,Aurangabad,Thailand,...,Economy,33C,PNR1028137,44625,2231.25,46856.25,Debit Card,Paid,Confirmed,12
CUST001548,5498,1548,2025-10-24,Rachana Sabharwal,F,32.0,2155039061.0,dateanamika@example.net,Pimpri-Chinchwad,UAE,...,Business,4F,PNR1758138,55615,2780.75,58395.75,Net Banking,Paid,Cancelled,13
CUST004960,5499,4960,2026-05-11,Waida Yadav,M,68.0,2139323697.0,demo#mail.com,Mysore,UAE,...,Business,20C,PNR8515395,26254,1312.70,27566.70,UPI,Refunded,Waiting,13

In [78]:
# sample()

# Used to randomly select rows from a DataFrame.
df.sample(5)

,index,BookingID,BookingDate,CustomerName,Gender,Age,MobileNo,EmailID,City,Country,...,SeatClass,SeatNumber,PNRNumber,TicketPrice,TaxAmount,TotalAmount,PaymentMode,PaymentStatus,BookingStatus,Name_Length
CustomerID,,,,,,,,,,,,,,,,,,,,,
CUST004634,1879,4634,2026-01-14,Gaurangi Konda,M,31.0,5363704699.0,sachdevmason@example.org,Tirunelveli,UAE,...,First Class,26C,PNR9225221,53804,2690.20,56494.20,Debit Card,Refunded,Waiting,9
CUST003920,2996,3920,2026-06-12,Daksh Muni,M,51.0,1818444953.0,finn09@example.net,Panvel,Thailand,...,Premium Economy,37B,NaN,-14996,2962.70,62216.70,UPI,Pending,Cancelled,8
CUST001931,1111,1931,2025-11-10,NaN,M,24.0,6796609270.0,gauri99@example.org,Ranchi,UK,...,Economy,7F,PNR7357085,73079,3653.95,76732.95,Debit Card,NaN,Waiting,18
CUST001683,3485,1683,2026-04-17,Divya Sachdeva,F,20.0,2159529753.0,NaN,Gandhinagar,UAE,...,Business,39B,PNR5887476,55964,2798.20,58762.20,UPI,NaN,Waiting,9
CUST000836,2776,836,2026-05-08,Oliver Kunda,M,NaN,NaN,NaN,Bhiwani,India,...,Business,1E,PNR8942308,60309,3015.45,63324.45,Net Banking,Pending,Confirmed,18

In [79]:
# nunique()

# Returns the number of unique values.
df['City'].nunique()

316

In [81]:
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')

df['Age_Group'] = np.where(
    df['Age'] >= 18,
    'Adult',
    'Minor'
)

df[['Age', 'Age_Group']].head()

             Age Age_Group
CustomerID
CUST001690  48.0     Adult
CUST002399  33.0     Adult
CUST001181  30.0     Adult
CUST002506  48.0     Adult
CUST001496  58.0     Adult

In [82]:
# np.select()

# Used when you have multiple conditions.
conditions = [
    df['Age'] < 18,
    df['Age'].between(18, 59),
    df['Age'] >= 60
]

choices = [
    'Minor',
    'Adult',
    'Senior'
]

df['Age_Group'] = np.select(
    conditions,
    choices,
    default='Unknown'
)

In [83]:
# np.quantile()

# Used to calculate quantiles/percentiles of numerical data.
np.quantile(df['Age'], 0.25)

np.float64(nan)