<div class="alert alert-block alert-info">
<b>Flight Booking Advanced </b>
</div>

In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(r"D:\data-science-journey\Data_Science\Data\Flight_Booking_Advanced_Dirty_Dataset_5500_Records.csv")

In [3]:
df.head()

,BookingID,BookingDate,CustomerID,CustomerName,Gender,Age,MobileNo,EmailID,City,Country,...,ArrivalTime,SeatClass,SeatNumber,PNRNumber,TicketPrice,TaxAmount,TotalAmount,PaymentMode,PaymentStatus,BookingStatus
0,1690,2025-11-25,CUST001690,Bahadurjit Swamy,Male,48.0,4630329843.0,rgoda@example.com,Berhampore,UK,...,19:00,First Class,40A,PNR7922321,24610,1230.50,25840.50,Net Banking,Pending,Waiting
1,2399,2026-05-21,CUST002399,NaN,Female,33.0,9420542745.0,om95@example.com,Mysore,Thailand,...,08:30,Economy,10F,PNR1694734,71893,3594.65,75487.65,Debit Card,Refunded,Waiting
2,1181,2025-11-04,CUST001181,Diya Goel,Female,30.0,3844774388.0,samraindira@example.net,Medininagar,UK,...,04:00,Business,49B,PNR1281400,67601,3380.05,70981.05,Debit Card,Pending,Waiting
3,2506,2026-05-30,CUST002506,Omya Varkey,Female,48.0,3151414768.0,user@,Satara,India,...,00:45,First Class,32C,PNR8326876,40021,2001.05,42022.05,Credit Card,Pending,NaN
4,1496,2025-06-25,CUST001496,Tanmayi Apte,Female,58.0,5194803805.0,NaN,Imphal,UK,...,14:45,NaN,37D,PNR9053659,69585,3479.25,73064.25,Credit Card,Refunded,Waiting

# __Section A: Data Cleaning & Preprocessing__

In [4]:
# first 10 records 
# last 10 records 
df.head(10)
df.tail(10)

,BookingID,BookingDate,CustomerID,CustomerName,Gender,Age,MobileNo,EmailID,City,Country,...,ArrivalTime,SeatClass,SeatNumber,PNRNumber,TicketPrice,TaxAmount,TotalAmount,PaymentMode,PaymentStatus,BookingStatus
5490,3830,2026-01-12,CUST003830,Hiral Sastry,Male,69.0,4224148229.0,lakshit68@example.net,NaN,UK,...,17:30,Economy,15A,PNR7864663,42700,2135.00,44835.00,Credit Card,NaN,Waiting
5491,3818,2025-09-14,CUST003818,NaN,Female,67.0,7495136410.0,wahabvenkatesh@example.com,Sambhal,Singapore,...,23:00,Economy,49C,PNR7697291,34881,1744.05,36625.05,Net Banking,Refunded,Cancelled
5492,2624,2026-02-13,CUST002624,Ansh Acharya,Female,-5,3274178213.0,suhanirao@example.com,Hosur,India,...,04:15,Premium Economy,11A,PNR8777437,59882,2994.10,62876.10,Debit Card,Pending,Waiting
5493,974,2025-09-15,CUST000974,Ayaan Atwal,Male,50.0,5616294328.0,barkha35@example.com,Gangtok,UAE,...,21:45,Premium Economy,39A,PNR5012714,28353,1417.65,29770.65,UPI,Refunded,Cancelled
5494,4080,2026-04-03,CUST004080,Oeshi Chaudhary,Female,39.0,4736401874.0,agarwalutkarsh@example.net,Bathinda,UK,...,12:30,Premium Economy,46C,PNR6113573,10841,542.05,11383.05,Debit Card,Pending,Confirmed
5495,4172,2026-01-05,CUST004172,Gayathri Ram,Female,39.0,6442065575.0,abcgmail.com,Shimoga,India,...,13:30,Economy,12B,PNR3576254,11601,580.05,12181.05,Net Banking,Refunded,Waiting
5496,600,2026-01-13,CUST000600,Veda Reddy,Female,63.0,4801278694.0,demo#mail.com,Satna,Singapore,...,04:45,Business,49D,PNR3086789,3612,180.60,3792.60,Credit Card,Pending,Confirmed
5497,1362,2026-06-01,CUST001362,Max Natt,Male,52.0,6262413293.0,ucchalvyas@example.org,Aurangabad,Thailand,...,01:00,Economy,33C,PNR1028137,44625,2231.25,46856.25,Debit Card,Paid,Confirmed
5498,1548,2025-10-24,CUST001548,Rachana Sabharwal,Female,32.0,2155039061.0,dateanamika@example.net,Pimpri-Chinchwad,UAE,...,03:45,Business,4F,PNR1758138,55615,2780.75,58395.75,Net Banking,Paid,Cancelled
5499,4960,2026-05-11,CUST004960,Waida Yadav,Male,68.0,2139323697.0,demo#mail.com,Mysore,UAE,...,17:30,Business,20C,PNR8515395,26254,1312.70,27566.70,UPI,Refunded,Waiting

In [5]:
# total no. of row & col
df.shape

(5500, 29)

In [6]:
# col names 
df.columns

Index(['BookingID', 'BookingDate', 'CustomerID', 'CustomerName', 'Gender',
       'Age', 'MobileNo', 'EmailID', 'City', 'Country', 'FlightID',
       'FlightName', 'FlightNumber', 'SourceCity', 'SourceAirport',
       'DestinationCity', 'DestinationAirport', 'FlightDate', 'DepartureTime',
       'ArrivalTime', 'SeatClass', 'SeatNumber', 'PNRNumber', 'TicketPrice',
       'TaxAmount', 'TotalAmount', 'PaymentMode', 'PaymentStatus',
       'BookingStatus'],
      dtype='object')

In [7]:
# numerical col 
df.select_dtypes(include=['number']).columns.to_list()

['BookingID', 'TicketPrice', 'TaxAmount', 'TotalAmount']

In [8]:
# dtype of col
df.dtypes

BookingID               int64
BookingDate            object
CustomerID             object
CustomerName           object
Gender                 object
Age                    object
MobileNo               object
EmailID                object
City                   object
Country                object
FlightID               object
FlightName             object
FlightNumber           object
SourceCity             object
SourceAirport          object
DestinationCity        object
DestinationAirport     object
FlightDate             object
DepartureTime          object
ArrivalTime            object
SeatClass              object
SeatNumber             object
PNRNumber              object
TicketPrice             int64
TaxAmount             float64
TotalAmount           float64
PaymentMode            object
PaymentStatus          object
BookingStatus          object
dtype: object

In [9]:
# nan valuse 
df.isnull().sum().sum()

np.int64(5986)

In [10]:
# nan valuse col wise 
df.isnull().sum()

BookingID               0
BookingDate             0
CustomerID              0
CustomerName          934
Gender                  0
Age                   578
MobileNo              521
EmailID               535
City                  226
Country                 0
FlightID                0
FlightName              0
FlightNumber            0
SourceCity            555
SourceAirport           0
DestinationCity       543
DestinationAirport      0
FlightDate            530
DepartureTime           0
ArrivalTime             0
SeatClass             561
SeatNumber              0
PNRNumber             223
TicketPrice             0
TaxAmount               0
TotalAmount             0
PaymentMode             0
PaymentStatus         556
BookingStatus         224
dtype: int64

In [11]:
# Display records having at least one NULL value
df[df.isnull().any(axis=1)]

,BookingID,BookingDate,CustomerID,CustomerName,Gender,Age,MobileNo,EmailID,City,Country,...,ArrivalTime,SeatClass,SeatNumber,PNRNumber,TicketPrice,TaxAmount,TotalAmount,PaymentMode,PaymentStatus,BookingStatus
0,1690,2025-11-25,CUST001690,Bahadurjit Swamy,Male,48.0,4630329843.0,rgoda@example.com,Berhampore,UK,...,19:00,First Class,40A,PNR7922321,24610,1230.50,25840.50,Net Banking,Pending,Waiting
1,2399,2026-05-21,CUST002399,NaN,Female,33.0,9420542745.0,om95@example.com,Mysore,Thailand,...,08:30,Economy,10F,PNR1694734,71893,3594.65,75487.65,Debit Card,Refunded,Waiting
2,1181,2025-11-04,CUST001181,Diya Goel,Female,30.0,3844774388.0,samraindira@example.net,Medininagar,UK,...,04:00,Business,49B,PNR1281400,67601,3380.05,70981.05,Debit Card,Pending,Waiting
3,2506,2026-05-30,CUST002506,Omya Varkey,Female,48.0,3151414768.0,user@,Satara,India,...,00:45,First Class,32C,PNR8326876,40021,2001.05,42022.05,Credit Card,Pending,NaN
4,1496,2025-06-25,CUST001496,Tanmayi Apte,Female,58.0,5194803805.0,NaN,Imphal,UK,...,14:45,NaN,37D,PNR9053659,69585,3479.25,73064.25,Credit Card,Refunded,Waiting
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5487,909,2026-05-05,CUST000909,Jonathan Chaudhry,Male,49.0,9618179394.0,gardeharinakshi@example.com,Suryapet,India,...,07:15,First Class,10A,PNR7468291,41770,2088.50,43858.50,UPI,Pending,Confirmed
5490,3830,2026-01-12,CUST003830,Hiral Sastry,Male,69.0,4224148229.0,lakshit68@example.net,NaN,UK,...,17:30,Economy,15A,PNR7864663,42700,2135.00,44835.00,Credit Card,NaN,Waiting
5491,3818,2025-09-14,CUST003818,NaN,Female,67.0,7495136410.0,wahabvenkatesh@example.com,Sambhal,Singapore,...,23:00,Economy,49C,PNR7697291,34881,1744.05,36625.05,Net Banking,Refunded,Cancelled
5492,2624,2026-02-13,CUST002624,Ansh Acharya,Female,-5,3274178213.0,suhanirao@example.com,Hosur,India,...,04:15,Premium Economy,11A,PNR8777437,59882,2994.10,62876.10,Debit Card,Pending,Waiting
5499,4960,2026-05-11,CUST004960,Waida Yadav,Male,68.0,2139323697.0,demo#mail.com,Mysore,UAE,...,17:30,Business,20C,PNR8515395,26254,1312.70,27566.70,UPI,Refunded,Waiting

In [12]:
#  Calculate percentage of missing values per column. 
df.isnull().mean().round(3)*100

BookingID              0.0
BookingDate            0.0
CustomerID             0.0
CustomerName          17.0
Gender                 0.0
Age                   10.5
MobileNo               9.5
EmailID                9.7
City                   4.1
Country                0.0
FlightID               0.0
FlightName             0.0
FlightNumber           0.0
SourceCity            10.1
SourceAirport          0.0
DestinationCity        9.9
DestinationAirport     0.0
FlightDate             9.6
DepartureTime          0.0
ArrivalTime            0.0
SeatClass             10.2
SeatNumber             0.0
PNRNumber              4.1
TicketPrice            0.0
TaxAmount              0.0
TotalAmount            0.0
PaymentMode            0.0
PaymentStatus         10.1
BookingStatus          4.1
dtype: float64

In [13]:
df.fillna("Null")
numeric_cols = df.select_dtypes(include="number").columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())

In [14]:
# Remove leading and trailing spaces from CustomerName
df['CustomerName'] = df['CustomerName'].str.strip()

In [15]:
# FlightName to uperrcase & lowercase 
df['FlightName'].str.upper()
df['FlightName'].str.lower()

0       singapore airlines
1           etihad airways
2                akasa air
3                lufthansa
4                 emirates
               ...
5495               vistara
5496              emirates
5497          thai airways
5498         qatar airways
5499         qatar airways
Name: FlightName, Length: 5500, dtype: object

In [16]:
# Standerdize filght name 
df['FlightName'] = df['FlightName'].str.title()

In [17]:
# Identify inconsistent city names. 
df['City'].value_counts()

City
Ghaziabad     39
Aurangabad    29
Buxar         27
Hajipur       27
Shivpuri      26
              ..
Gulbarga       8
Maheshtala     8
Vijayawada     7
Panvel         7
Madurai        5
Name: count, Length: 316, dtype: int64

In [18]:
# Correct spelling mistakes in FlightName. 

df["FlightName"].unique()
df['FlightName'].replace({
    "INDIGO ":"IndiGO",
    "indigo":"IndiGO",
    "vistara123":"Vistara",
    " Air India":"Air India"
},inplace=True)

C:\Users\pyugp\AppData\Local\Temp\ipykernel_22732\2822090250.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['FlightName'].replace({

In [19]:
# Display records having extra spaces.
df[df.apply(lambda row: row.astype(str).str.endswith(" ").any(), axis=1)]

,BookingID,BookingDate,CustomerID,CustomerName,Gender,Age,MobileNo,EmailID,City,Country,...,ArrivalTime,SeatClass,SeatNumber,PNRNumber,TicketPrice,TaxAmount,TotalAmount,PaymentMode,PaymentStatus,BookingStatus
137,4998,2025-07-13,CUST004998,NaN,Male,42.0,6587876977.0,ubhatnagar@example.org,Bhusawal,Singapore,...,22:45,NaN,38B,PNR2376083,58007,2900.35,60907.35,Net Banking,Pending,Cancelled
239,640,2026-04-02,CUST000640,NaN,Male,NaN,6555935317.0,bsibal@example.net,Singrauli,India,...,10:30,Business,16D,PNR3544310,16211,810.55,17021.55,Net Banking,Refunded,Waiting
292,2935,2025-09-05,CUST002935,NaN,Female,30.0,3115266983.0,george76@example.com,Srinagar,UK,...,00:00,Business,40E,PNR2250401,17935,896.75,18831.75,Credit Card,NaN,Cancelled
362,1166,2025-07-05,CUST001166,NaN,Male,75.0,2621467174.0,user@,Vellore,Singapore,...,20:00,First Class,4D,PNR5515251,13049,652.45,13701.45,Net Banking,Paid,Confirmed
605,1270,2025-07-01,CUST001270,Wazir Som,Male,48.0,4086538590.0,NaN,Pune,UAE,...,20:00,NaN,15B,PNR7466603,41001,2050.05,43051.05,Net Banking,NaN,Cancelled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4857,1313,2025-10-11,CUST001313,Chandresh Dash,Male,44.0,8511201227.0,jyoti76@example.com,Kollam,Thailand,...,09:15,First Class,17C,PNR5624716,9791,489.55,10280.55,Debit Card,Paid,Confirmed
4942,807,2026-02-13,CUST000807,Chandresh Bal,Female,55.0,345465567.0,garima09@example.net,Khora,Thailand,...,07:30,Business,30A,PNR6655248,57813,2890.65,60703.65,Net Banking,Refunded,Cancelled
4991,2199,2025-07-31,CUST002199,Krish Banik,Male,35.0,NaN,sankarandrew@example.org,Kolkata,UAE,...,01:30,First Class,24F,PNR7315405,28035,1401.75,29436.75,UPI,Refunded,Waiting
5021,3971,2026-02-13,CUST003971,Qushi Manda,Female,60.0,8291032926.0,balakrishnandamini@example.net,Sirsa,Thailand,...,09:30,First Class,40F,PNR4125038,10120,506.00,10626.00,UPI,Paid,Waiting
5410,633,2025-12-27,CUST000633,Gabriel Toor,Female,34.0,7959561979.0,qasimyogi@example.net,Naihati,India,...,02:30,Economy,14A,PNR3449052,58897,2944.85,61841.85,Debit Card,Refunded,Cancelled

In [20]:
#  Remove duplicate records.
df.drop_duplicates()

,BookingID,BookingDate,CustomerID,CustomerName,Gender,Age,MobileNo,EmailID,City,Country,...,ArrivalTime,SeatClass,SeatNumber,PNRNumber,TicketPrice,TaxAmount,TotalAmount,PaymentMode,PaymentStatus,BookingStatus
0,1690,2025-11-25,CUST001690,Bahadurjit Swamy,Male,48.0,4630329843.0,rgoda@example.com,Berhampore,UK,...,19:00,First Class,40A,PNR7922321,24610,1230.50,25840.50,Net Banking,Pending,Waiting
1,2399,2026-05-21,CUST002399,NaN,Female,33.0,9420542745.0,om95@example.com,Mysore,Thailand,...,08:30,Economy,10F,PNR1694734,71893,3594.65,75487.65,Debit Card,Refunded,Waiting
2,1181,2025-11-04,CUST001181,Diya Goel,Female,30.0,3844774388.0,samraindira@example.net,Medininagar,UK,...,04:00,Business,49B,PNR1281400,67601,3380.05,70981.05,Debit Card,Pending,Waiting
3,2506,2026-05-30,CUST002506,Omya Varkey,Female,48.0,3151414768.0,user@,Satara,India,...,00:45,First Class,32C,PNR8326876,40021,2001.05,42022.05,Credit Card,Pending,NaN
4,1496,2025-06-25,CUST001496,Tanmayi Apte,Female,58.0,5194803805.0,NaN,Imphal,UK,...,14:45,NaN,37D,PNR9053659,69585,3479.25,73064.25,Credit Card,Refunded,Waiting
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5495,4172,2026-01-05,CUST004172,Gayathri Ram,Female,39.0,6442065575.0,abcgmail.com,Shimoga,India,...,13:30,Economy,12B,PNR3576254,11601,580.05,12181.05,Net Banking,Refunded,Waiting
5496,600,2026-01-13,CUST000600,Veda Reddy,Female,63.0,4801278694.0,demo#mail.com,Satna,Singapore,...,04:45,Business,49D,PNR3086789,3612,180.60,3792.60,Credit Card,Pending,Confirmed
5497,1362,2026-06-01,CUST001362,Max Natt,Male,52.0,6262413293.0,ucchalvyas@example.org,Aurangabad,Thailand,...,01:00,Economy,33C,PNR1028137,44625,2231.25,46856.25,Debit Card,Paid,Confirmed
5498,1548,2025-10-24,CUST001548,Rachana Sabharwal,Female,32.0,2155039061.0,dateanamika@example.net,Pimpri-Chinchwad,UAE,...,03:45,Business,4F,PNR1758138,55615,2780.75,58395.75,Net Banking,Paid,Cancelled
5499,4960,2026-05-11,CUST004960,Waida Yadav,Male,68.0,2139323697.0,demo#mail.com,Mysore,UAE,...,17:30,Business,20C,PNR8515395,26254,1312.70,27566.70,UPI,Refunded,Waiting

In [21]:
# Count duplicate records. 
df.drop_duplicates().count()

BookingID             5000
BookingDate           5000
CustomerID            5000
CustomerName          4533
Gender                5000
Age                   4470
MobileNo              4523
EmailID               4521
City                  4800
Country               5000
FlightID              5000
FlightName            5000
FlightNumber          5000
SourceCity            4500
SourceAirport         5000
DestinationCity       4500
DestinationAirport    5000
FlightDate            4517
DepartureTime         5000
ArrivalTime           5000
SeatClass             4500
SeatNumber            5000
PNRNumber             4800
TicketPrice           5000
TaxAmount             5000
TotalAmount           5000
PaymentMode           5000
PaymentStatus         4500
BookingStatus         4800
dtype: int64

In [22]:
# Find duplicate PNR Numbers
df['PNRNumber'].duplicated().sum()

np.int64(701)

In [23]:
df['PNRNumber'] = df['PNRNumber'].drop_duplicates()

In [24]:
# remove rows containing more than 50% null values. 
df.isnull().mean().round(4)*100

BookingID              0.00
BookingDate            0.00
CustomerID             0.00
CustomerName          16.98
Gender                 0.00
Age                   10.51
MobileNo               9.47
EmailID                9.73
City                   4.11
Country                0.00
FlightID               0.00
FlightName             0.00
FlightNumber           0.00
SourceCity            10.09
SourceAirport          0.00
DestinationCity        9.87
DestinationAirport     0.00
FlightDate             9.64
DepartureTime          0.00
ArrivalTime            0.00
SeatClass             10.20
SeatNumber             0.00
PNRNumber             12.76
TicketPrice            0.00
TaxAmount              0.00
TotalAmount            0.00
PaymentMode            0.00
PaymentStatus         10.11
BookingStatus          4.07
dtype: float64

In [25]:
# Replace missing Age values using mean
df['Age'] = pd.to_numeric(df['Age'], errors='coerce') # errors='coerce' converts invalid values such as "unknown" or "N/A" into NaN
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [26]:
# Replace missing Age values using median
df['Age'] = df['Age'].fillna((df['Age'].median()))

In [27]:
# Replace missing SeatClass values using mode. 
df['SeatClass'] = df['SeatClass'].fillna((df['SeatClass'].mode()))

In [28]:
# Replace missing PaymentStatus with "Pending".
df['PaymentStatus'] =df['PaymentStatus'].fillna("Pending")

In [29]:
# Replace missing FlightDate with BookingDate. 
df['FlightDate']= df['FlightDate'].fillna(df['BookingDate'])

In [30]:
# Standardize SeatClass names. 
df['SeatClass'].unique()

array(['First Class', 'Economy', 'Business', nan, 'Premium Economy'],
      dtype=object)

In [31]:
# Identify invalid PaymentStatus values. 
df['PaymentStatus']

0        Pending
1       Refunded
2        Pending
3        Pending
4       Refunded
          ...
5495    Refunded
5496     Pending
5497        Paid
5498        Paid
5499    Refunded
Name: PaymentStatus, Length: 5500, dtype: object

In [32]:
df["PaymentStatus"].unique()

array(['Pending', 'Refunded', 'Paid'], dtype=object)

In [33]:
# Identify invalid Gender values. 
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [34]:
# Convert all string columns to title case. 
object_col =df.select_dtypes(include="object")
df[object_col.columns] = object_col.apply(lambda col: col.str.title())

In [35]:
df.to_csv("cleaned_dataset2.csv", index=False)

In [36]:
# Create a cleaned copy of dataset.
cleaned_df = df.copy()

In [37]:
#  Export cleaned dataset to CSV. 
cleaned_df.to_csv("cleaned_dataset.csv", index=False)

In [38]:
# 38.Compare original and cleaned dataset size.
# 39.Display records modified during cleaning. 
print("Original dataset size:", df.shape)
print("Cleaned dataset size:", cleaned_df.shape)

Original dataset size: (5500, 29)
Cleaned dataset size: (5500, 29)

In [39]:
modified = df.ne(cleaned_df).any(axis=1)
cleaned_df[modified]

,BookingID,BookingDate,CustomerID,CustomerName,Gender,Age,MobileNo,EmailID,City,Country,...,ArrivalTime,SeatClass,SeatNumber,PNRNumber,TicketPrice,TaxAmount,TotalAmount,PaymentMode,PaymentStatus,BookingStatus
0,1690,2025-11-25,Cust001690,Bahadurjit Swamy,Male,48.0,4630329843.0,Rgoda@Example.Com,Berhampore,Uk,...,19:00,First Class,40A,Pnr7922321,24610,1230.50,25840.50,Net Banking,Pending,Waiting
1,2399,2026-05-21,Cust002399,NaN,Female,33.0,9420542745.0,Om95@Example.Com,Mysore,Thailand,...,08:30,Economy,10F,Pnr1694734,71893,3594.65,75487.65,Debit Card,Refunded,Waiting
2,1181,2025-11-04,Cust001181,Diya Goel,Female,30.0,3844774388.0,Samraindira@Example.Net,Medininagar,Uk,...,04:00,Business,49B,Pnr1281400,67601,3380.05,70981.05,Debit Card,Pending,Waiting
3,2506,2026-05-30,Cust002506,Omya Varkey,Female,48.0,3151414768.0,User@,Satara,India,...,00:45,First Class,32C,Pnr8326876,40021,2001.05,42022.05,Credit Card,Pending,NaN
4,1496,2025-06-25,Cust001496,Tanmayi Apte,Female,58.0,5194803805.0,NaN,Imphal,Uk,...,14:45,NaN,37D,Pnr9053659,69585,3479.25,73064.25,Credit Card,Refunded,Waiting
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5486,4574,2025-09-04,Cust004574,Indrajit Trivedi,Female,22.0,NaN,Lcheema@Example.Org,Rajkot,Uae,...,17:45,Business,35A,Pnr3966526,46808,2340.40,49148.40,Credit Card,Refunded,Confirmed
5487,909,2026-05-05,Cust000909,Jonathan Chaudhry,Male,49.0,9618179394.0,Gardeharinakshi@Example.Com,Suryapet,India,...,07:15,First Class,10A,Pnr7468291,41770,2088.50,43858.50,Upi,Pending,Confirmed
5490,3830,2026-01-12,Cust003830,Hiral Sastry,Male,69.0,4224148229.0,Lakshit68@Example.Net,NaN,Uk,...,17:30,Economy,15A,Pnr7864663,42700,2135.00,44835.00,Credit Card,Pending,Waiting
5491,3818,2025-09-14,Cust003818,NaN,Female,67.0,7495136410.0,Wahabvenkatesh@Example.Com,Sambhal,Singapore,...,23:00,Economy,49C,NaN,34881,1744.05,36625.05,Net Banking,Refunded,Cancelled
5499,4960,2026-05-11,Cust004960,Waida Yadav,Male,68.0,2139323697.0,Demo#Mail.Com,Mysore,Uae,...,17:30,Business,20C,Pnr8515395,26254,1312.70,27566.70,Upi,Refunded,Waiting

In [40]:
# 40.Generate a data cleaning summary report. 

print("Original Shape:", df.shape)
print("Cleaned Shape:", cleaned_df.shape)
print("Modified Records:", modified.sum())
print("Missing Before:", df.isnull().sum().sum())
print("Missing After:", cleaned_df.isnull().sum().sum())

Original Shape: (5500, 29)
Cleaned Shape: (5500, 29)
Modified Records: 3097
Missing Before: 4801
Missing After: 4801

# Section B: Handling Missing Values

In [41]:
# Count null values in CustomerName and EmailID ,MobileNo,FlightDate,SourceCity ,DestinationCity
df[['CustomerName', 'EmailID','MobileNo','FlightDate','SourceCity','DestinationCity']].isnull().sum()

CustomerName       934
EmailID            535
MobileNo           521
FlightDate           0
SourceCity         555
DestinationCity    543
dtype: int64

In [42]:
# Display rows where EmailID is missing. 
df[df['EmailID'].isnull()]

,BookingID,BookingDate,CustomerID,CustomerName,Gender,Age,MobileNo,EmailID,City,Country,...,ArrivalTime,SeatClass,SeatNumber,PNRNumber,TicketPrice,TaxAmount,TotalAmount,PaymentMode,PaymentStatus,BookingStatus
4,1496,2025-06-25,Cust001496,Tanmayi Apte,Female,58.000000,5194803805.0,NaN,Imphal,Uk,...,14:45,NaN,37D,Pnr9053659,69585,3479.25,73064.25,Credit Card,Refunded,Waiting
20,2452,2025-07-15,Cust002452,Aishani Raman,Female,39.000000,5958976887.0,NaN,Patiala,Uae,...,08:45,First Class,39B,Pnr6877833,66445,3322.25,69767.25,Credit Card,Paid,Confirmed
30,317,2026-05-09,Cust000317,NaN,Female,53.000000,7187846166.0,NaN,Ahmednagar,Uk,...,02:30,Economy,41A,Pnr9757413,2880,144.00,3024.00,Credit Card,Refunded,Confirmed
48,3771,2025-07-08,Cust003771,Rajata Hegde,Male,58.000000,8632401011.0,NaN,Mysore,Uae,...,21:45,First Class,41C,Pnr9558494,36179,1808.95,37987.95,Net Banking,Paid,Waiting
57,3256,2026-04-09,Cust003256,NaN,Female,46.000000,4348034097.0,NaN,Surendranagar Dudhrej,Thailand,...,17:15,Business,41D,NaN,73030,3651.50,76681.50,Credit Card,Pending,Confirmed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5452,3485,2025-11-23,Cust003485,NaN,Female,47.778967,NaN,NaN,Phusro,India,...,08:45,First Class,8F,NaN,60892,3044.60,63936.60,Credit Card,Pending,Confirmed
5455,4609,2026-02-17,Cust004609,Varenya Manda,Male,72.000000,8860590132.0,NaN,Thoothukudi,Singapore,...,01:15,NaN,8F,Pnr2511197,62171,3108.55,65279.55,Net Banking,Paid,Waiting
5467,3749,2025-06-25,Cust003749,Girish Basak,Male,74.000000,2791971017.0,NaN,Parbhani,India,...,08:30,Premium Economy,29E,Pnr3659634,0,1198.70,25172.70,Credit Card,Pending,Confirmed
5475,1274,2025-09-12,Cust001274,Reyansh Shah,Female,67.000000,98765,NaN,Rajahmundry,Uae,...,11:15,First Class,23E,Pnr5899016,32074,1603.70,33677.70,Debit Card,Pending,Cancelled
5481,4468,2025-08-19,Cust004468,Harinakshi Bains,Male,58.000000,9717860293.0,NaN,Hospet,Uae,...,17:15,Economy,45E,Pnr9750886,33021,1651.05,34672.05,Net Banking,Pending,Cancelled

In [43]:
# Replace missing EmailID with "Not Available"
df['EmailID'] = df['EmailID'].fillna('Not Available')

In [44]:
# Replace missing MobileNo with "0000000000".
df['MobileNo'] = df['MobileNo'].fillna(0000000000)

In [45]:
# .Replace missing Age with average age. 
# df['Age'] = df['Age'].fillna(df['Age'].mean())

In [46]:
# .Replace missing SourceCity with "Unknown". 
df['SourceCity'] = df['SourceCity'].fillna('Unknown')

In [47]:
# .Replace missing DestinationCity with "Unknown". 
df['DestinationCity'] = df['DestinationCity'].fillna('Unknown')

In [48]:
# Replace missing FlightDate with current date
from datetime import date

today = date.today()
print(today)  
df['FlightDate'] = df['FlightDate'].fillna(today)

2026-09-15

In [49]:
# .Remove rows containing missing CustomerName. 
df['CustomerName'] = df['CustomerName'].dropna()

In [50]:
# Remove rows containing missing EmailID. 
df['EmailID'] = df['EmailID'].dropna()
df['EmailID'].count()

np.int64(5500)

In [51]:
# Display columns with at least 10% missing values
ten_per=df.isnull().mean().round(3)*100
col_name =ten_per[ten_per >= 10]
df[col_name.index]

           CustomerName    SeatClass   PNRNumber
0      Bahadurjit Swamy  First Class  Pnr7922321
1                   NaN      Economy  Pnr1694734
2             Diya Goel     Business  Pnr1281400
3           Omya Varkey  First Class  Pnr8326876
4          Tanmayi Apte          NaN  Pnr9053659
...                 ...          ...         ...
5495       Gayathri Ram      Economy  Pnr3576254
5496         Veda Reddy     Business  Pnr3086789
5497           Max Natt      Economy  Pnr1028137
5498  Rachana Sabharwal     Business  Pnr1758138
5499        Waida Yadav     Business  Pnr8515395

[5500 rows x 3 columns]

In [52]:
# Fill null Age using forward fill. 

df['Age'] = df['Age'].backfill()

C:\Users\pyugp\AppData\Local\Temp\ipykernel_22732\3464726884.py:3: FutureWarning: DataFrame.backfill/Series.backfill is deprecated. Use DataFrame.bfill/Series.bfill instead
  df['Age'] = df['Age'].backfill()

In [53]:
# Fill null SeatClass using mode. 

df['SeatClass'] = df['SeatClass'].mode()

In [54]:
# .Create indicator column for missing MobileNo. 
df['MobileNo_Missing'] = df['MobileNo'].isnull()

In [55]:
# Count rows having multiple missing values.
count = (df.isnull().sum(axis=1) > 1).sum()
count

np.int64(1478)

In [56]:
# Display top 20 rows containing maximum missing values. 
(df.isnull().sum(axis=1) > 3).sum()

np.int64(53)

In [57]:
# Create missing value summary table
missing_summary = pd.DataFrame({
    'Missing Values': df.isnull().sum(),
    'Percentage': df.isnull().mean() * 100
})

missing_summary

                    Missing Values  Percentage
BookingID                        0    0.000000
BookingDate                      0    0.000000
CustomerID                       0    0.000000
CustomerName                   934   16.981818
Gender                           0    0.000000
Age                              0    0.000000
MobileNo                         0    0.000000
EmailID                          0    0.000000
City                           226    4.109091
Country                          0    0.000000
FlightID                         0    0.000000
FlightName                       0    0.000000
FlightNumber                     0    0.000000
SourceCity                       0    0.000000
SourceAirport                    0    0.000000
DestinationCity                  0    0.000000
DestinationAirport               0    0.000000
FlightDate                       0    0.000000
DepartureTime                    0    0.000000
ArrivalTime                      0    0.000000
SeatClass                     5499   99.981818
SeatNumber                       0    0.000000
PNRNumber                      702   12.763636
TicketPrice                      0    0.000000
TaxAmount                        0    0.000000
TotalAmount                      0    0.000000
PaymentMode                      0    0.000000
PaymentStatus                    0    0.000000
BookingStatus                  224    4.072727
MobileNo_Missing                 0    0.000000

In [58]:
original_df = df.copy()
numeric_cols = df.select_dtypes(include="number").columns

df[numeric_cols] = df[numeric_cols].fillna(
    df[numeric_cols].mean()
)
comparison = pd.DataFrame({
    "Before": original_df.isnull().sum(),
    "After": df.isnull().sum()
})

comparison

                    Before  After
BookingID                0      0
BookingDate              0      0
CustomerID               0      0
CustomerName           934    934
Gender                   0      0
Age                      0      0
MobileNo                 0      0
EmailID                  0      0
City                   226    226
Country                  0      0
FlightID                 0      0
FlightName               0      0
FlightNumber             0      0
SourceCity               0      0
SourceAirport            0      0
DestinationCity          0      0
DestinationAirport       0      0
FlightDate               0      0
DepartureTime            0      0
ArrivalTime              0      0
SeatClass             5499   5499
SeatNumber               0      0
PNRNumber              702    702
TicketPrice              0      0
TaxAmount                0      0
TotalAmount              0      0
PaymentMode              0      0
PaymentStatus            0      0
BookingStatus          224    224
MobileNo_Missing         0      0

# Section D: Data Validation Rules

In [59]:
# Validate EmailID format. 
import re

pattern = r'^[\w\.-]+@[\w\.-]+\.\w+$'

df['Email_Valid'] = df['EmailID'].astype(str).str.match(pattern)

df['Email_Valid']

0        True
1        True
2        True
3       False
4       False
        ...
5495    False
5496    False
5497     True
5498     True
5499    False
Name: Email_Valid, Length: 5500, dtype: bool

In [60]:
# Validate mobile no. format. 
df['MobileNo_Valid'] = df['MobileNo'].astype(str).str.fullmatch(r'\d{10}')

In [61]:
# .Validate CustomerName length. 
df['CustomerName_Valid'] = df['CustomerName'].str.len()>=3

In [62]:
# Validate Age range between 18 and 80. 
df['Age_Valid'] = df['Age'].ge(18) & df['Age'].le(80)

In [63]:
df['BookingDate_Valid'] = pd.to_datetime(
    df['BookingDate'],
    format='%Y-%m-%d',
    errors='coerce'
).notna()

In [64]:
df['FlightNumber_Valid'] = df['FlightNumber'].astype(str).str.fullmatch(r'[A-Za-z]{2}\d{3,4}')

In [65]:
df['TicketPrice_Valid'] = df['TicketPrice'].gt(0)

In [66]:
valid_status = ['Paid', 'Pending', 'Failed']

df['PaymentStatus_Valid'] = df['PaymentStatus'].isin(valid_status)

In [67]:
valid_status = ['Confirmed', 'Cancelled', 'Waiting']

df['BookingStatus_Valid'] = df['BookingStatus'].isin(valid_status)